#!/usr/bin/env bash
# Generate dev embedded Node Agent mTLS + write dev/cellp-elastic.env (AD-15).
# Usage: ./dev/scripts/elastic-dev-init.sh
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

CERT_DIR="${ROOT}/dev/data/certs/elastic"
ENV_FILE="${ROOT}/dev/cellp-elastic.env"

mkdir -p "$CERT_DIR"
echo "==> genelasticdevcerts -> ${CERT_DIR}"
(cd "$ROOT/cellp" && GOTOOLCHAIN=local go run ./cmd/genelasticdevcerts --dir "$CERT_DIR") >/dev/null

NODE_ID="local-dev-node"
CTRL_URI="spiffe://cellp/local/controller/main"
NODE_URI="spiffe://cellp/local/node/${NODE_ID}"
AGENT_BIND="127.0.0.1:19443"

cat >"$ENV_FILE" <<EOF
# Generated by dev/scripts/elastic-dev-init.sh — source from dev/scripts/up.sh
export CELLP_AGENT_EMBEDDED=1
export CELLP_AGENT_NODE_ID=${NODE_ID}
export CELLP_AGENT_BIND_ADDR=${AGENT_BIND}
export CELLP_AGENT_ADVERTISE_URL=https://${AGENT_BIND}
export CELLP_AGENT_ALLOW_PRIVATE_NAT=false
export CELLP_AGENT_NODE_IDENTITY_URI=${NODE_URI}
export CELLP_AGENT_CONTROLLER_IDENTITY_URI=${CTRL_URI}
export CELLP_AGENT_ALLOWED_CONTROLLER_URIS=${CTRL_URI}
export CELLP_AGENT_SERVER_CERT_FILE=${CERT_DIR}/agent-server.pem
export CELLP_AGENT_SERVER_KEY_FILE=${CERT_DIR}/agent-server-key.pem
export CELLP_AGENT_SERVER_CA_FILE=${CERT_DIR}/ca.pem
export CELLP_AGENT_CLIENT_CERT_FILE=${CERT_DIR}/agent-client.pem
export CELLP_AGENT_CLIENT_KEY_FILE=${CERT_DIR}/agent-client-key.pem
export CELLP_AGENT_CLIENT_CA_FILE=${CERT_DIR}/ca.pem
export CELLP_AGENT_TLS_SERVER_NAME=127.0.0.1
export CELLP_AGENT_CERT_DENYLIST_FILE=${CERT_DIR}/denylist.pem
export CELLP_AGENT_CAPACITY_UNITS=8
export CELLP_AGENT_ZONE=local-dev
export CELLP_AGENT_HEARTBEAT_TTL=30s
export CELLP_AGENT_HEARTBEAT_INTERVAL=10s
export CELLP_AGENT_RECONCILE_INTERVAL=5s
export CELLP_AGENT_MAX_BODY_BYTES=1048576
export CELLP_AGENT_REPLAY_MAX_ENTRIES=4096
EOF

echo "Wrote ${ENV_FILE}"
echo "Next: ./dev/scripts/build-cellpd.sh && CELLP_RESTART_CELLPD=1 ./dev/scripts/up.sh --fast"
